Fix loadMarketDataForTicker function
We were passing the result of loadExbitronDataForToken(ticker) (a promise)
directly to coreApi.getMarketDataForToken instead of passing the function
reference itself.

```
Error processing items: TypeError: functionToCall is not a function
    at Object.tryCacheThenCallFunction (file:///explorer/app/api/cacheApi.js:194:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async processLoadingOfData (file:///explorer/app/api/marketDataApi.js:52:18)
    at async Object.loadMarketDataForTicker (file:///explorer/app/api/marketDataApi.js:29:25)
```